In [33]:
from pathlib import Path
import sys
import pandas as pd

In [ ]:
project_root = Path.cwd()

if project_root.name == "notebooks":
    project_root = project_root.parent

sys.path.insert(0, str(project_root))
from src.database import get_engine
from sqlalchemy import text
import os
import getpass

os.environ["PGUSER"] = "sgurung"
os.environ["PGDATABASE"] = "citibike"
os.environ["PGPASSWORD"] = getpass.getpass("PostgreSQL password: ")

In [ ]:
engine = get_engine()
with engine.connect() as conn:
        hourly_neighborhood_flow = pd.read_sql(text(
            f"""
            Select *
            from "hourly_neighborhood_flow"
            """
        ), con=conn)
        hourly_weather_history= pd.read_sql(text(
            f"""
            Select *
            from "hourly_weather_history"
            """
        ), con=conn)
engine.dispose()

In [36]:
hourly_neighborhood_flow.head()

,hour,nta_code,nta_name,borough,departures,arrivals,net_flow
0,2024-12-30 23:00:00,QN0103,Astoria (Central),Queens,1.0,0.0,-1.0
1,2024-12-31 00:00:00,BK0103,South Williamsburg,Brooklyn,1.0,0.0,-1.0
2,2024-12-31 10:00:00,BK5591,Prospect Park,Brooklyn,1.0,0.0,-1.0
3,2024-12-31 11:00:00,BK0101,Greenpoint,Brooklyn,1.0,0.0,-1.0
4,2024-12-31 12:00:00,BK0102,Williamsburg,Brooklyn,1.0,0.0,-1.0

In [37]:
hourly_weather_history.head()

,hour,temperature,dew_point,precipitation,snowfall,weather_code,wind_speed
0,2024-12-29 23:00:00,13.00,11.70,0.0,0.0,3.0,22.614190
1,2024-12-30 00:00:00,13.00,11.45,0.5,0.0,53.0,22.450264
2,2024-12-30 01:00:00,13.00,11.50,0.1,0.0,51.0,25.502893
3,2024-12-30 02:00:00,12.75,11.85,3.4,0.0,63.0,22.686426
4,2024-12-30 03:00:00,12.50,11.85,1.2,0.0,55.0,15.367616

In [38]:
hourly_neighborhood_flow.isna().sum()

hour          0
nta_code      0
nta_name      0
borough       0
departures    0
arrivals      0
net_flow      0
dtype: int64

In [39]:
merged_data = pd.merge(hourly_neighborhood_flow, hourly_weather_history, how="left", on="hour")
merged_data.head()

,hour,nta_code,nta_name,borough,departures,arrivals,net_flow,temperature,dew_point,precipitation,snowfall,weather_code,wind_speed
0,2024-12-30 23:00:00,QN0103,Astoria (Central),Queens,1.0,0.0,-1.0,7.2,1.40,0.0,0.0,0.0,11.465024
1,2024-12-31 00:00:00,BK0103,South Williamsburg,Brooklyn,1.0,0.0,-1.0,6.4,1.35,0.0,0.0,0.0,10.534229
2,2024-12-31 10:00:00,BK5591,Prospect Park,Brooklyn,1.0,0.0,-1.0,5.7,1.75,0.0,0.0,0.0,1.800000
3,2024-12-31 11:00:00,BK0101,Greenpoint,Brooklyn,1.0,0.0,-1.0,7.6,2.70,0.0,0.0,1.0,2.255393
4,2024-12-31 12:00:00,BK0102,Williamsburg,Brooklyn,1.0,0.0,-1.0,9.2,3.30,0.0,0.0,2.0,4.711050

In [ ]:
engine = get_engine()
with engine.connect() as conn:
        neighborhood_hourly_model_data = pd.read_sql(text(
            f"""
            Select *
            from "neighborhood_hourly_model_data"
            """
        ), con=conn)

engine.dispose()
neighborhood_hourly_model_data.head()

,hour,nta_code,nta_name,borough,departures,arrivals,net_flow,temperature,dew_point,precipitation,snowfall,weather_code,wind_speed
0,2024-12-30 23:00:00,QN0103,Astoria (Central),Queens,1.0,0.0,-1.0,7.2,1.40,0.0,0.0,0.0,11.465024
1,2024-12-31 00:00:00,BK0103,South Williamsburg,Brooklyn,1.0,0.0,-1.0,6.4,1.35,0.0,0.0,0.0,10.534229
2,2024-12-31 10:00:00,BK5591,Prospect Park,Brooklyn,1.0,0.0,-1.0,5.7,1.75,0.0,0.0,0.0,1.800000
3,2024-12-31 11:00:00,BK0101,Greenpoint,Brooklyn,1.0,0.0,-1.0,7.6,2.70,0.0,0.0,1.0,2.255393
4,2024-12-31 12:00:00,BK0102,Williamsburg,Brooklyn,1.0,0.0,-1.0,9.2,3.30,0.0,0.0,2.0,4.711050